# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CG_taller_nbdev',
                'doc_host': 'https://UrielMendoza.github.io',
                'git_url': 'https://github.com/UrielMendoza/CG_taller_nbdev',
                'lib_path': 'CG_taller_nbdev'},
  'syms': {'CG_taller_nbdev.core': {'CG_taller_nbdev.core.foo': ('core.html#foo', 'CG_taller_nbdev/core.py')}}}
